version: '3'
services:
  backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      DB_NAME: shopify_sync_db
      DB_HOST: db
      DB_PORT: 5432
    expose:
      - 8000
    ports:
      - '8000:8000'
    depends_on:
      - db
    volumes:
      - .:/app/backend

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    env_file:
      - .env
    ports:
      - '8080:8080'
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend


  db:
    image: postgres:15-alpine3.18
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

volumes:
  postgres_data:
