services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile_dev
    environment:
      VUE_APP_BACKEND_HOST: http://localhost:8000
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app

  backend:
    restart: no
    environment:
      DB_HOST: host.docker.internal
    command: >
      sh -c "python manage.py collectstatic --no-input &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - redis
    volumes:
      - .:/app

  celery:
    restart: no
    environment:
      DB_HOST: host.docker.internal
    command: python -m celery -A app worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    restart: no

  nginx:
    entrypoint: [ "echo", "Service foo disabled" ]
    restart: no

  db:
    entrypoint: [ "echo", "Service foo disabled" ]
    restart: no