# Generated by Django 4.2.1 on 2023-06-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdatasource',
            name='processor',
            field=models.CharField(choices=[('Fuse5Processor', 'Fuse 5'), ('CustomCSVProcessor', 'Custom CSV')], max_length=20),
        ),
    ]
