# Generated by Django 4.2.2 on 2023-06-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_sync', '0002_alter_stockdatasource_processor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.PositiveBigIntegerField(db_index=True)),
                ('source', models.CharField(max_length=30)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('sku', models.CharField()),
                ('product_id', models.PositiveBigIntegerField(null=True)),
                ('variant_id', models.PositiveBigIntegerField()),
                ('changes', models.JSONField()),
            ],
        ),
    ]
