# Generated by Django 4.2.2 on 2023-07-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_sync', '0003_productsupdatelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCsvData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
