# Generated by Django 4.2.2 on 2023-07-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_sync', '0004_customcsvdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsupdatelog',
            name='barcode',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
