# Generated by Django 4.2.2 on 2023-08-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_sync', '0005_productsupdatelog_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuse5Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=20, null=True)),
                ('price', models.FloatField(null=True)),
                ('inventory_quantity', models.IntegerField(null=True)),
                ('sku', models.CharField(max_length=30, null=True)),
                ('line_code', models.CharField(max_length=3, null=True)),
                ('product_name', models.CharField(null=True)),
                ('location_name', models.CharField(max_length=30, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['barcode'], name='products_sy_barcode_c1929c_idx')],
            },
        ),
    ]
