# Generated by Django 4.2.2 on 2023-10-08 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('products_sync', '0009_unmatchedproductsforreview_shopify_product_title'),
    ]

    operations = [
        migrations.DeleteModel(name='customcsvdata'),

        migrations.CreateModel(
            name='CustomCsv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),

        migrations.CreateModel(
            name='CustomCsvData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_csv',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_sync.customcsv')),
                ('barcode', models.CharField(max_length=20, null=True)),
                ('price', models.FloatField(null=True)),
                ('inventory_quantity', models.IntegerField(null=True)),
                ('sku', models.CharField(max_length=30, null=True)),
                ('location_name', models.CharField(max_length=30, null=True)),
            ],
            options={
                'indexes': [
                    models.Index(fields=['barcode'], name='products_sy_barcode_07a3fc_idx'),
                    models.Index(fields=['sku'], name='products_sy_sku_4a9750_idx'),
                ],
            },
        ),
    ]
